idf_component_register(
    SRCS
        "main.c"
        "wifi_manager.c"
        "nvs_storage.c"
        "http_client.c"
        "http_client_utils.c"
        "deadman_timer.c"
        "relay_controller.c"
    INCLUDE_DIRS "."
    REQUIRES
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        esp_http_server
        esp_http_client
        esp_tls
        esp_timer
        cjson
    EMBED_TXTFILES
        "certs/root_cert.pem"
)
