"""Initial schema: users, bunkers, devices, device_status, time_window_overrides, weather_data, global_config

Revision ID: 78c833ebcaf5
Revises: 
Create Date: 2025-10-23 17:22:13.799397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c833ebcaf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunkers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('orientation_degrees', sa.Float(), nullable=False),
    sa.Column('fan_count', sa.Integer(), nullable=False),
    sa.Column('wind_threshold_mph', sa.Float(), nullable=True),
    sa.Column('electricity_cost_kwh', sa.Float(), nullable=False),
    sa.Column('fan_power_watts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fan_count > 0', name='check_fan_count'),
    sa.CheckConstraint('orientation_degrees >= 0 AND orientation_degrees < 360', name='check_orientation'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_wind_threshold_mph', sa.Float(), nullable=False),
    sa.Column('default_electricity_cost_kwh', sa.Float(), nullable=False),
    sa.Column('default_fan_power_watts', sa.Integer(), nullable=False),
    sa.Column('weather_station_id', sa.String(length=10), nullable=False),
    sa.Column('weather_poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('shutdown_broadcast_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('device_offline_threshold_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='check_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        sa.text(
            """
            INSERT INTO global_config (
                id,
                default_wind_threshold_mph,
                default_electricity_cost_kwh,
                default_fan_power_watts,
                weather_station_id,
                weather_poll_interval_seconds,
                shutdown_broadcast_interval_seconds,
                device_offline_threshold_seconds
            )
            VALUES (1, 15.0, 0.12, 1500, 'KOKC', 60, 60, 120)
            """
        )
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weather_data',
    sa.Column('station_id', sa.String(length=10), nullable=False),
    sa.Column('wind_speed_mph', sa.Float(), nullable=False),
    sa.Column('wind_direction_degrees', sa.Float(), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('wind_direction_degrees >= 0 AND wind_direction_degrees < 360', name='check_wind_direction'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('auth_token', sa.Uuid(), nullable=False),
    sa.Column('bunker_id', sa.Uuid(), nullable=False),
    sa.Column('fan_position', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('led_flash_sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint('led_flash_sequence BETWEEN 1 AND 10', name='check_led_flash_sequence'),
    sa.ForeignKeyConstraint(['bunker_id'], ['bunkers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bunker_id', 'fan_position', name='uq_bunker_fan_position')
    )
    op.create_index('idx_devices_bunker_id', 'devices', ['bunker_id'], unique=False)
    op.create_index('idx_devices_last_seen', 'devices', ['last_seen'], unique=False)
    op.create_index(op.f('ix_devices_auth_token'), 'devices', ['auth_token'], unique=True)
    op.create_index(op.f('ix_devices_bunker_id'), 'devices', ['bunker_id'], unique=False)
    op.create_index(op.f('ix_devices_last_seen'), 'devices', ['last_seen'], unique=False)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_table('time_window_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bunker_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_time_window'),
    sa.ForeignKeyConstraint(['bunker_id'], ['bunkers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_status',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('relay_state', sa.String(length=10), nullable=False),
    sa.Column('uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('wifi_rssi', sa.Integer(), nullable=False),
    sa.Column('countdown_timer_remaining', sa.Integer(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_received_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("relay_state IN ('ON', 'OFF')", name='check_relay_state'),
    sa.CheckConstraint('countdown_timer_remaining BETWEEN 0 AND 300', name='check_countdown_timer'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_status')
    op.drop_table('time_window_overrides')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen'), table_name='devices')
    op.drop_index(op.f('ix_devices_bunker_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_auth_token'), table_name='devices')
    op.drop_index('idx_devices_last_seen', table_name='devices')
    op.drop_index('idx_devices_bunker_id', table_name='devices')
    op.drop_table('devices')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('global_config')
    op.drop_table('bunkers')
    # ### end Alembic commands ###
